import React from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = url && key ? createClient(url, key) : null;
const FN = url ? `${url}/functions/v1/admin-control-center` : '';

function ConfigError(){return <main className="auth"><section><b>ROYEXA</b><span>PRIVATE CONTROL CENTER</span><h1>Configuration required</h1><p className="error">The Admin Center is missing its Supabase environment variables. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel, then redeploy.</p></section></main>}
const call = async (body) => { const { data:{session} } = await supabase.auth.getSession(); if (!session) throw new Error('Not authenticated'); const r = await fetch(FN,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}); if(!r.ok) throw new Error(`Admin API error (${r.status})`); return r.json(); };
function Login(){const [email,setEmail]=React.useState('');const [pw,setPw]=React.useState('');const [code,setCode]=React.useState('');const [step,setStep]=React.useState('login');const [factor,setFactor]=React.useState(null);const [err,setErr]=React.useState('');
async function login(e){e.preventDefault();setErr('');const {error}=await supabase.auth.signInWithPassword({email,password:pw});if(error)return setErr(error.message);const {data:ok,error:ae}=await supabase.rpc('is_security_admin');if(ae)return setErr(ae.message);if(!ok){await supabase.auth.signOut();return setErr('Not authorized as security administrator.');}const {data:f}=await supabase.auth.mfa.listFactors();const v=(f?.totp||[]).find(x=>x.status==='verified');if(!v)return setErr('Admin 2-step verification is not enrolled yet.');const {data:a}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(a.currentLevel==='aal2'){location.reload();return;}const {error:ce}=await supabase.auth.mfa.challenge({factorId:v.id});if(ce)return setErr(ce.message);setFactor(v.id);setStep('mfa');}
async function verify(e){e.preventDefault();const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code});if(error)return setErr(error.message);location.reload();}
return <main className="auth"><section><b>ROYEXA</b><span>PRIVATE CONTROL CENTER</span><h1>Admin access</h1>{step==='login'?<form onSubmit={login}><input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Admin password" value={pw} onChange={e=>setPw(e.target.value)} required/><button>Continue</button></form>:<form onSubmit={verify}><p>Enter the 6-digit code from your authenticator.</p><input inputMode="numeric" maxLength="6" placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><button>Verify</button></form>}{err&&<div className="error">{err}</div>}</section></main>}
function Dashboard(){const [data,setData]=React.useState(null);const [err,setErr]=React.useState('');const [tab,setTab]=React.useState('overview');React.useEffect(()=>{call({action:'read'}).then(setData).catch(e=>setErr(e.message))},[]);if(err)return <main className="auth"><section><b>ROYEXA</b><span>SECURITY ERROR</span><h1>Unable to load Control Center</h1><div className="error">{err}</div></section></main>;if(!data)return <main className="loading">Loading secure telemetry…</main>;return <main className="dash"><header><div><b>ROYEXA SECURITY</b><h1>Control Center</h1></div><button onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>Sign out</button></header><nav>{['overview','incidents','enforcement','teams'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>{tab==='overview'&&<section className="cards"><article><small>INTRUSIONS</small><strong>{data.alerts?.length||0}</strong></article><article><small>BLOCKS</small><strong>{data.blocks?.length||0}</strong></article><article><small>ENFORCEMENTS</small><strong>{data.enforcements?.length||0}</strong></article><article><small>TEAMS</small><strong>{data.teams?.length||0}</strong></article></section>}{tab==='incidents'&&<section className="panel"><h2>Intrusion alerts</h2>{(data.alerts||[]).map(a=><div className="row" key={a.id}><b>{a.event_type}</b><span>{a.endpoint||'unknown'} · {a.risk_score}/100</span></div>)}</section>}{tab==='enforcement'&&<section className="panel"><h2>Enforcement</h2>{(data.enforcements||[]).map(a=><div className="row" key={a.id}><b>{a.action}</b><span>{a.reason} · {a.user_id}</span></div>)}</section>}{tab==='teams'&&<section className="panel"><h2>Teams</h2>{(data.teams||[]).map(t=><div className="row" key={t.id}><b>{t.name}</b><span>{t.description||''}</span></div>)}</section>}</main>}
async function App(){if(!supabase)return <ConfigError/>;const {data:{session}}=await supabase.auth.getSession();if(!session)return <Login/>;const {data:ok,error}=await supabase.rpc('is_security_admin');if(error||!ok){await supabase.auth.signOut();return <Login/>;}const {data:a}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(a.currentLevel!=='aal2')return <Login/>;return <Dashboard/>}
createRoot(document.getElementById('root')).render(<App/>);