import React from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = url && key ? createClient(url, key) : null;
const ADMIN_URL = window.location.origin;

function Shell({children}) { return <main className="auth"><section><b>ROYEXA</b><span>SECURITY CONSOLE</span>{children}</section></main>; }
function Setup() { return <Shell><h1>Admin setup incomplete</h1><p className="error">The security console is not connected to its database yet. Check the Supabase URL and publishable key in Vercel, then redeploy.</p></Shell>; }

function ForgotPassword(){const [email,setEmail]=React.useState('');const [sent,setSent]=React.useState(false);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${ADMIN_URL}/reset-password`});if(error)throw error;setSent(true);}catch(err){setError(err?.message||'Unable to send reset email.')}finally{setBusy(false)}};return <Shell><h1>Reset Admin password</h1>{sent?<><p>Check your email for the password reset link. It will return you to this Admin Console.</p><button onClick={()=>setSent(false)}>Send again</button></>:<form onSubmit={submit}><p>Enter the email used for your Admin account.</p><input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><button type="submit" disabled={busy}>{busy?'Sending…':'Send reset link'}</button></form>}{error&&<div className="error">{error}</div>}</Shell>}

function ResetPassword({onDone}){const [password,setPassword]=React.useState('');const [confirm,setConfirm]=React.useState('');const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const submit=async e=>{e.preventDefault();setError('');if(password.length<8){setError('Password must be at least 8 characters.');return;}if(password!==confirm){setError('Passwords do not match.');return;}setBusy(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;await supabase.auth.signOut();onDone();}catch(err){setError(err?.message||'Unable to update password.')}finally{setBusy(false)}};return <Shell><h1>Set new Admin password</h1><form onSubmit={submit}><input type="password" placeholder="New password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" required/><input type="password" placeholder="Confirm password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/><button type="submit" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>{error&&<div className="error">{error}</div>}</Shell>}

function Enrollment({onDone}) {const [factorId,setFactorId]=React.useState('');const [qr,setQr]=React.useState('');const [secret,setSecret]=React.useState('');const [code,setCode]=React.useState('');const [busy,setBusy]=React.useState(true);const [error,setError]=React.useState('');const [starting,setStarting]=React.useState(true);
React.useEffect(()=>{let mounted=true;(async()=>{try{const {data:factors,error:listError}=await supabase.auth.mfa.listFactors();if(listError)throw listError;for(const f of (factors?.totp||[])){if(f.status!=='verified'){const {error:removeError}=await supabase.auth.mfa.unenroll({factorId:f.id});if(removeError)throw removeError;}}
const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'ROYEXA Admin'});if(error)throw error;if(!mounted)return;setFactorId(data.id);setQr(data.totp?.qr_code||'');setSecret(data.totp?.secret||'');}catch(err){if(mounted)setError(err?.message||'Unable to start two-step verification setup.')}finally{if(mounted){setBusy(false);setStarting(false)}}})();return()=>{mounted=false}},[]);
const verify=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data:challenge,error:challengeError}=await supabase.auth.mfa.challenge({factorId});if(challengeError)throw challengeError;const {error:verifyError}=await supabase.auth.mfa.verify({factorId,challengeId:challenge.id,code});if(verifyError)throw verifyError;onDone();}catch(err){setError(err?.message||'Invalid verification code.')}finally{setBusy(false)}};
const qrSrc=qr?(qr.trim().startsWith('data:image/')?qr.trim():qr.trim().startsWith('<svg')?`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`):'';
return <Shell><h1>Set up 2-step verification</h1><p>Scan the QR code with an authenticator app, then enter the 6-digit code.</p>{qrSrc?<img src={qrSrc} alt="Authenticator QR code" style={{width:220,height:220,background:'#fff',padding:12,borderRadius:12,display:'block'}} onError={()=>setError('The QR code could not be rendered. Use the manual setup key below.')} />:<p>{starting?'Preparing secure setup…':'QR code unavailable — use the manual setup key below.'}</p>}{secret&&<div><p><small>Manual setup key:</small></p><code style={{display:'block',wordBreak:'break-all',fontSize:14}}>{secret}</code><p><small>In your authenticator app choose <b>Enter setup key</b>, use this key, and select <b>Time based</b>.</small></p></div>}<form onSubmit={verify}><input inputMode="numeric" autoComplete="one-time-code" maxLength="6" placeholder="Enter 6-digit code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><button type="submit" disabled={busy||!factorId}>{busy?'Verifying…':'Enable 2-step verification'}</button></form>{error&&<div className="error">{error}</div>}<button type="button" disabled={busy} onClick={()=>window.location.reload()}>Start over</button></Shell>}

function Login({onDone}){const [email,setEmail]=React.useState('');const [password,setPassword]=React.useState('');const [code,setCode]=React.useState('');const [factor,setFactor]=React.useState(null);const [mfa,setMfa]=React.useState(false);const [enroll,setEnroll]=React.useState(false);const [forgot,setForgot]=React.useState(false);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');const signIn=async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;const {data:admin,error:adminError}=await supabase.rpc('is_security_admin');if(adminError)throw adminError;if(!admin){await supabase.auth.signOut();throw new Error('This account is not authorized for the security console.');}const {data:factors,error:factorError}=await supabase.auth.mfa.listFactors();if(factorError)throw factorError;const verified=(factors?.totp||[]).find(f=>f.status==='verified');if(!verified){setEnroll(true);return;}const {data:aal,error:aalError}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aalError)throw aalError;if(aal.currentLevel==='aal2'){onDone();return;}const {error:challengeError}=await supabase.auth.mfa.challenge({factorId:verified.id});if(challengeError)throw challengeError;setFactor(verified.id);setMfa(true);}catch(err){setError(err?.message||'Unable to sign in.')}finally{setBusy(false)}};const verify=async e=>{e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw error;onDone();}catch(err){setError(err?.message||'Invalid verification code.')}finally{setBusy(false)}};if(forgot)return <ForgotPassword/>;if(enroll)return <Enrollment onDone={onDone}/>;return <Shell><h1>Administrator sign in</h1>{!mfa?<form onSubmit={signIn}><input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="submit" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><button type="button" onClick={()=>setForgot(true)}>Forgot password?</button></form>:<form onSubmit={verify}><p>Enter the 6-digit code from your authenticator.</p><input inputMode="numeric" autoComplete="one-time-code" maxLength="6" placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><button type="submit" disabled={busy}>{busy?'Verifying…':'Verify'}</button></form>}{error&&<div className="error">{error}</div>}</Shell>}

function Dashboard({onSignOut}){const [tab,setTab]=React.useState('overview');const [data,setData]=React.useState({alerts:[],blocks:[],enforcements:[],teams:[]});const [error,setError]=React.useState('');React.useEffect(()=>{(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Session expired. Please sign in again.');const r=await fetch(`${url}/functions/v1/admin-control-center`,{method:'GET',headers:{Authorization:`Bearer ${session.access_token}`}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Security service returned ${r.status}`);setData(body);}catch(e){setError(e.message);}})();},[]);return <main className="dash"><header><div><b>ROYEXA SECURITY</b><h1>Control Center</h1></div><button onClick={onSignOut}>Sign out</button></header>{error&&<div className="error">{error}</div>}<nav>{['overview','incidents','enforcement','teams'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>{tab==='overview'&&<section className="cards"><article><small>INTRUSIONS</small><strong>{data.alerts?.length||0}</strong></article><article><small>BLOCKS</small><strong>{data.blocks?.length||0}</strong></article><article><small>ENFORCEMENTS</small><strong>{data.enforcements?.length||0}</strong></article><article><small>TEAMS</small><strong>{data.teams?.length||0}</strong></article></section>}{tab==='incidents'&&<section className="panel"><h2>Intrusion alerts</h2>{(data.alerts||[]).map(a=><div className="row" key={a.id}><b>{a.event_type}</b><span>{a.endpoint||'unknown'} · {a.risk_score}/100</span></div>)}</section>}{tab==='enforcement'&&<section className="panel"><h2>Enforcement</h2>{(data.enforcements||[]).map(a=><div className="row" key={a.id}><b>{a.action}</b><span>{a.reason} · {a.user_id}</span></div>)}</section>}{tab==='teams'&&<section className="panel"><h2>Teams</h2>{(data.teams||[]).map(t=><div className="row" key={t.id}><b>{t.name}</b><span>{t.description||''}</span></div>)}</section>}</main>}

function App(){const [ready,setReady]=React.useState(false);const [authorized,setAuthorized]=React.useState(false);const [reset,setReset]=React.useState(window.location.pathname==='/reset-password');React.useEffect(()=>{if(!supabase){setReady(true);return;}let mounted=true;(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session){if(mounted)setReady(true);return;}const {data:admin,error:adminError}=await supabase.rpc('is_security_admin');if(adminError)throw adminError;const {data:aal,error:aalError}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aalError)throw aalError;if(admin&&aal.currentLevel==='aal2'&&mounted)setAuthorized(true);}catch(e){if(mounted)setAuthorized(false);}finally{if(mounted)setReady(true);}})();const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'&&mounted)setReset(true);});return()=>{mounted=false;subscription.unsubscribe();};},[]);if(!supabase)return <Setup/>;if(reset)return <ResetPassword onDone={()=>{window.history.replaceState({},'', '/');setReset(false)}}/>;if(!ready)return <Shell><h1>Security console</h1><p>Checking your access…</p></Shell>;if(!authorized)return <Login onDone={()=>setAuthorized(true)}/>;return <Dashboard onSignOut={async()=>{await supabase.auth.signOut();setAuthorized(false)}}/>;}
createRoot(document.getElementById('root')).render(<App/>);