import React from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

function Shell({children}){return <main className="auth"><section><b>ROYEXA</b><span>SECURITY CONSOLE</span>{children}</section></main>}
const url=import.meta.env.VITE_SUPABASE_URL;const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
function ConfigError(){return <Shell><h1>Admin setup incomplete</h1><p className="error">The security console is not connected to its database yet. Please check the Supabase connection settings in Vercel and redeploy.</p></Shell>}
function Login({supabase}){const [email,setEmail]=React.useState('');const [pw,setPw]=React.useState('');const [code,setCode]=React.useState('');const [step,setStep]=React.useState('login');const [factor,setFactor]=React.useState(null);const [err,setErr]=React.useState('');
async function login(e){e.preventDefault();setErr('');try{const {error}=await supabase.auth.signInWithPassword({email,password:pw});if(error)throw error;const {data:ok,error:ae}=await supabase.rpc('is_security_admin');if(ae)throw ae;if(!ok){await supabase.auth.signOut();throw new Error('This account is not authorized for the security console.')}const {data:f,error:fe}=await supabase.auth.mfa.listFactors();if(fe)throw fe;const v=(f?.totp||[]).find(x=>x.status==='verified');if(!v)throw new Error('Two-step verification has not been enrolled for this admin account.');const {data:a}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(a.currentLevel==='aal2'){location.reload();return}const {error:ce}=await supabase.auth.mfa.challenge({factorId:v.id});if(ce)throw ce;setFactor(v.id);setStep('mfa')}catch(e){setErr(e?.message||'Unable to sign in')}}
async function verify(e){e.preventDefault();setErr('');const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code});if(error)return setErr(error.message);location.reload()}
return <Shell><h1>Administrator sign in</h1>{step==='login'?<form onSubmit={login}><input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={pw} onChange={e=>setPw(e.target.value)} required/><button>Sign in</button></form>:<form onSubmit={verify}><p>Enter the 6-digit code from your authenticator.</p><input inputMode="numeric" maxLength="6" placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><button>Verify</button></form>}{err&&<div className="error">{err}</div>}</Shell>}
function Dashboard({supabase}){const [data,setData]=React.useState(null);const [err,setErr]=React.useState('');const [tab,setTab]=React.useState('overview');React.useEffect(()=>{(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Session expired');const r=await fetch(`${url}/functions/v1/admin-control-center`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'read'})});if(!r.ok)throw new Error(`Security service returned ${r.status}`);setData(await r.json())}catch(e){setErr(e.message)}})()},[supabase]);if(err)return <Shell><h1>Security console unavailable</h1><div className="error">{err}</div></Shell>;if(!data)return <main className="loading">Loading security data…</main>;return <main className="dash"><header><div><b>ROYEXA SECURITY</b><h1>Control Center</h1></div><button onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>Sign out</button></header><nav>{['overview','incidents','enforcement','teams'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>{tab==='overview'&&<section className="cards"><article><small>INTRUSIONS</small><strong>{data.alerts?.length||0}</strong></article><article><small>BLOCKS</small><strong>{data.blocks?.length||0}</strong></article><article><small>ENFORCEMENTS</small><strong>{data.enforcements?.length||0}</strong></article><article><small>TEAMS</small><strong>{data.teams?.length||0}</strong></article></section>}{tab==='incidents'&&<section className="panel"><h2>Intrusion alerts</h2>{(data.alerts||[]).map(a=><div className="row" key={a.id}><b>{a.event_type}</b><span>{a.endpoint||'unknown'} · {a.risk_score}/100</span></div>)}</section>}{tab==='enforcement'&&<section className="panel"><h2>Enforcement</h2>{(data.enforcements||[]).map(a=><div className="row" key={a.id}><b>{a.action}</b><span>{a.reason} · {a.user_id}</span></div>)}</section>}{tab==='teams'&&<section className="panel"><h2>Teams</h2>{(data.teams||[]).map(t=><div className="row" key={t.id}><b>{t.name}</b><span>{t.description||''}</span></div>)}</section>}</main>}
function App(){if(!url||!key)return <ConfigError/>;const supabase=createClient(url,key);const [ready,setReady]=React.useState(false);const [session,setSession]=React.useState(null);const [authorized,setAuthorized]=React.useState(false);React.useEffect(()=>{let mounted=true;(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!mounted)return;if(!session){setReady(true);return}const {data:ok}=await supabase.rpc('is_security_admin');const {data:a}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(ok&&a.currentLevel==='aal2'){setSession(session);setAuthorized(true)}else await supabase.auth.signOut()}catch(e){}finally{if(mounted)setReady(true)}})();return()=>{mounted=false}},[]);if(!ready)return <Shell><h1>Security console</h1><p>Checking your access…</p></Shell>;if(!session||!authorized)return <Login supabase={supabase}/>;return <Dashboard supabase={supabase}/>}
createRoot(document.getElementById('root')).render(<App/>);