import React from 'react';

export default function TeamMemberForm({supabase,url,rpc,onClose,onSuccess,onError}) {
 const [form,setForm]=React.useState({name:'',email:'',department_id:'',position_id:'',team_id:'',phone:'',start_date:'',notes:''});
 const [departments,setDepartments]=React.useState([]),[positions,setPositions]=React.useState([]),[teams,setTeams]=React.useState([]),[busy,setBusy]=React.useState(false);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 React.useEffect(()=>{(async()=>{try{const[d,p,t]=await Promise.all([rpc('admin_list_departments'),rpc('admin_list_positions',{p_department_id:null}),rpc('admin_list_teams')]);setDepartments(d||[]);setPositions(p||[]);setTeams(t||[])}catch(e){onError(e.message)}})()},[]);
 React.useEffect(()=>{if(!form.department_id){rpc('admin_list_positions',{p_department_id:null}).then(setPositions).catch(e=>onError(e.message));return}rpc('admin_list_positions',{p_department_id:form.department_id}).then(setPositions).catch(e=>onError(e.message))},[form.department_id]);
 const submit=async e=>{e.preventDefault();setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw Error('Admin session expired. Sign in again.');const r=await fetch(`${url}/functions/v1/admin-create-team-member`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(form)});const out=await r.json();if(!r.ok)throw Error(out.error||'Unable to create team member');onSuccess(out.invited?'Team member created and invitation sent.':'Team member assigned successfully.');}catch(e){onError(e.message)}finally{setBusy(false)}};
 const ordered=[...positions].sort((a,b)=>{const leadA=a.permission_level==='lead'?0:1,leadB=b.permission_level==='lead'?0:1;return leadA-leadB||a.name.localeCompare(b.name)});
 return <form className="panel" onSubmit={submit}><h3>Create Team Member</h3><input placeholder="Full name" value={form.name} onChange={e=>set('name',e.target.value)} required/><input type="email" placeholder="Email — invitation will be sent" value={form.email} onChange={e=>set('email',e.target.value)} required/><select value={form.department_id} onChange={e=>{set('department_id',e.target.value);set('position_id','')}} required><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={form.position_id} onChange={e=>set('position_id',e.target.value)} required><option value="">Select position</option>{ordered.map(p=><option key={p.id} value={p.id}>{p.permission_level==='lead'?'Team Lead — ':''}{p.name} · {p.permission_level}</option>)}</select><select value={form.team_id} onChange={e=>set('team_id',e.target.value)}><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input placeholder="Phone" value={form.phone} onChange={e=>set('phone',e.target.value)}/><input type="date" value={form.start_date} onChange={e=>set('start_date',e.target.value)}/><textarea placeholder="Notes" rows="4" value={form.notes} onChange={e=>set('notes',e.target.value)}/><div className="toolbar"><button type="submit" disabled={busy}>{busy?'Creating…':'Create & Send Invitation'}</button><button type="button" onClick={onClose}>Cancel</button></div></form>;
}