import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { createClient } from "@supabase/supabase-js";
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const GMAIL_FN="gmail-tasks-v3";
function isGmailTask(t){return /\b(gmail|email|emails|inbox|mail)\b/i.test(t)}
function gmailTaskFrom(t){const x=t.toLowerCase();if(/\b(search|find|look for)\b/.test(x))return{task:"search",query:t.replace(/.*?\b(search|find|look for)\b/i,"").replace(/\b(in|on)\s+(my\s+)?gmail\b/i,"").trim()};if(/\b(send|write|compose|draft).*\bemail\b/i.test(t))return{task:"send_request"};if(/\b(briefing|daily|today|important)\b/.test(x))return{task:"briefing"};if(/\b(summarize|summary|summarise)\b/.test(x))return{task:"summarize"};return{task:"inbox"}}
function formatEmails(es=[]){if(!es.length)return"I checked your Gmail, but there are no matching emails.";return es.map((e,i)=>`${i+1}. ${e.subject}\nFrom: ${e.from}\nDate: ${e.date}\n${e.snippet||""}`).join("\n\n")}
function Assistant(){const[open,setOpen]=useState(false),[input,setInput]=useState(""),[messages,setMessages]=useState([{role:"assistant",text:"Hi 👋 I’m your ROYEXA AI Assistant. Ask me about your CRM or tell me what to do with Gmail."}]),[leads,setLeads]=useState([]),[busy,setBusy]=useState(false),[pending,setPending]=useState(null),[error,setError]=useState("");
async function loadLeads(){const{data}=await supabase.from("leads").select("*").order("updated_at",{ascending:false});setLeads(data||[])}
useEffect(()=>{loadLeads();const h=()=>{setOpen(true);setError("")};window.addEventListener("royexa:assistant-open",h);return()=>window.removeEventListener("royexa:assistant-open",h)},[]);
const context=useMemo(()=>leads.slice(0,100).map(l=>({id:l.id,name:l.name,email:l.email,phone:l.phone,business_name:l.business_name,interest:l.interest,status:l.status,deal_value:l.deal_value,next_follow_up_at:l.next_follow_up_at})),[leads]);
async function gmail(task,p={}){const{data,error}=await supabase.functions.invoke(GMAIL_FN,{body:{task,...p}});if(error)throw Error(error.message||"Gmail task failed.");if(!data?.ok)throw Error(data?.error||"Gmail task failed.");return data}
async function runGmail(text){const task=gmailTaskFrom(text);if(task.task==="send_request"){setPending({to:"",subject:"",body:"",threadId:null});return"I’m ready to prepare the email. Enter the recipient, subject and message below, then review it before sending."}const data=await gmail(task.task,task.task==="search"?{query:task.query,limit:10}:{});if(task.task==="summarize"||task.task==="briefing"){const es=data.emails||[];if(!es.length)return"No recent emails to summarize.";const ai=await supabase.functions.invoke("ai-crm-assistant",{body:{action:"chat",message:`Analyze these Gmail messages. Give a concise business briefing with urgent items, people needing replies, deadlines, opportunities and risks. Do not invent facts.\n\n${JSON.stringify(es)}`,leads:context}});if(ai.error)throw Error(ai.error.message||"AI email analysis failed.");return ai.data?.result||formatEmails(es)}return task.task==="search"?`Gmail results for “${task.query}”:\n\n${formatEmails(data.emails)}`:`📧 Your latest Gmail\n\n${formatEmails(data.emails)}`}
async function sendApproved(){if(!pending?.to||!pending?.body){setError("Recipient and message are required.");return}setBusy(true);setError("");try{const r=await gmail("send_reply",{...pending,approved:true});setPending(null);setMessages(m=>[...m,{role:"assistant",text:`✓ Email sent successfully to ${pending.to}. Message ID: ${r.sent?.id||"sent"}`}])}catch(e){setError(e.message||"Email send failed.")}finally{setBusy(false)}}
async function sendMessage(e){e?.preventDefault();const text=input.trim();if(!text||busy)return;setInput("");setError("");setBusy(true);const next=[...messages,{role:"user",text}];setMessages(next);try{if(isGmailTask(text)){const r=await runGmail(text);setMessages(m=>[...m,{role:"assistant",text:r}]);return}const{data,error}=await supabase.functions.invoke("ai-crm-assistant",{body:{action:"chat",message:text,history:next.slice(-12),leads:context}});if(error)throw Error(error.message||"AI request failed.");if(!data?.ok)throw Error(data?.error||"AI request failed.");setMessages(m=>[...m,{role:"assistant",text:data.result||"No response."}])}catch(e){setError(e.message||"Task failed.")}finally{setBusy(false)}}
if(!open)return <button type="button" onClick={()=>setOpen(true)} style={fab}>🤖 AI Assistant</button>;
return <div style={panel}><div style={head}><div><strong>🤖 ROYEXA AI</strong><small> Assistant + Gmail</small></div><button type="button" onClick={()=>setOpen(false)} style={icon}>×</button></div><div style={body}>{messages.map((m,i)=><div key={i} style={m.role==="user"?userBubble:aiBubble}><b>{m.role==="user"?"You":"AI"}</b><div style={{whiteSpace:"pre-wrap",marginTop:5}}>{m.text}</div></div>)}{pending&&<div style={draftBox}><b>Review email before sending</b><input placeholder="Recipient email" value={pending.to} onChange={e=>setPending({...pending,to:e.target.value})}/><input placeholder="Subject" value={pending.subject} onChange={e=>setPending({...pending,subject:e.target.value})}/><textarea placeholder="Message" value={pending.body} onChange={e=>setPending({...pending,body:e.target.value})}/><button type="button" disabled={busy} onClick={sendApproved} style={approve}>Approve & Send</button><button type="button" onClick={()=>setPending(null)} style={cancel}>Cancel</button></div>}{error&&<div style={errorBox}>{error}</div>}{busy&&<div style={typing}>Working…</div>}</div><form onSubmit={sendMessage} style={composer}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask anything or give me a task…"/><button type="submit" disabled={busy||!input.trim()}>➤</button></form></div>}
const fab={position:"fixed",right:20,bottom:20,zIndex:9999,border:0,borderRadius:999,padding:"13px 17px",background:"#111",color:"#fff",fontWeight:700,boxShadow:"0 10px 30px rgba(0,0,0,.2)"};const panel={position:"fixed",right:20,bottom:20,width:"min(390px,calc(100vw - 32px))",height:"min(650px,calc(100vh - 40px))",zIndex:10000,background:"#0b0b0d",color:"#f5f5f7",border:"1px solid #2a2a2e",borderRadius:20,boxShadow:"0 20px 60px rgba(0,0,0,.6)",display:"flex",flexDirection:"column",overflow:"hidden",fontFamily:"Inter,system-ui,sans-serif"};const head={padding:"16px 18px",borderBottom:"1px solid #2a2a2e",display:"flex",justifyContent:"space-between"};const icon={border:0,background:"transparent",color:"#fff",fontSize:24};const body={flex:1,overflowY:"auto",padding:14};const userBubble={maxWidth:"88%",margin:"8px 0 8px auto",padding:12,borderRadius:"16px 16px 4px 16px",background:"#2563eb",color:"#fff"};const aiBubble={maxWidth:"92%",margin:"8px auto 8px 0",padding:12,borderRadius:"16px 16px 16px 4px",background:"#1b1b20",border:"1px solid #34343a"};const draftBox={margin:"12px 0",padding:12,borderRadius:14,background:"#201b0b",border:"1px solid #66551a"};const inputStyle={width:"100%",boxSizing:"border-box",margin:"6px 0",padding:9,borderRadius:8,border:"1px solid #555"};const approve={border:0,borderRadius:9,padding:"9px 12px",background:"#047857",color:"#fff",fontWeight:700};const cancel={marginLeft:8,padding:"9px 12px"};const errorBox={padding:10,color:"#ffb4b4"};const typing={padding:8,color:"#aaa"};const composer={display:"flex",gap:8,padding:12,borderTop:"1px solid #2a2a2e"};
function mount(){if(document.getElementById("royexa-ai-root"))return;const node=document.createElement("div");node.id="royexa-ai-root";document.body.appendChild(node);createRoot(node).render(<Assistant/>)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();