import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{createClient}from"@supabase/supabase-js";
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const groups=[{title:"WORKSPACE",items:[["dashboard","⌂","Home"],["leads","◎","Leads"],["messages","◌","Messages"],["followups","◷","Follow-ups"]]},{title:"CRM & TOOLS",items:[["calendar","□","Calendar"],["email","@","Gmail"],["whatsapp","◉","WhatsApp"],["analytics","◒","Analytics"],["intelligence","◈","Intelligence"],["automations","⚡","Automations"],["client","◇","CRM Tools"],["notifications","🔔","Notifications"],["post","＋","Make Post"]]}];
const emit=(name,detail)=>window.dispatchEvent(new CustomEvent(name,{detail}));
const base={fontFamily:"system-ui,-apple-system,sans-serif",boxSizing:"border-box"};
function existing(names){const all=[...document.querySelectorAll("button,a,[role='button']")].filter(x=>!x.closest("#royexa-mobile-nav-root")&&!x.closest("#royexa-home-root"));return all.find(el=>names.some(n=>(el.textContent||"").trim().toLowerCase().includes(n.toLowerCase())))}
function clickWhenReady(names){const hit=existing(names);if(hit){hit.click();return true}setTimeout(()=>{const retry=existing(names);if(retry)retry.click()},150);setTimeout(()=>{const retry=existing(names);if(retry)retry.click()},500);return false}
function route(id){if(id==="dashboard")return emit("royexa:home-open");const click=names=>clickWhenReady(names);if(id==="leads")return emit("royexa:leads-open");if(id==="messages")return emit("royexa:messages-open");if(id==="followups")return emit("royexa:followups-open");if(id==="email")return emit("royexa:gmail-open");if(id==="analytics")return emit("royexa:analytics-open");if(id==="automations")return emit("royexa:automations-open");if(id==="intelligence")return emit("royexa:intelligence-open");if(id==="calendar")return emit("royexa:calendar-open");if(id==="whatsapp")return emit("royexa:whatsapp-open");if(id==="client")return emit("royexa:client-tools");if(id==="notifications")return emit("royexa:notifications-open");if(id==="post")return emit("royexa:social-scheduler-open")}
function ChatPreview({chat,onOpen}){const msgs=Array.isArray(chat.messages)?chat.messages:[];const last=[...msgs].reverse().find(m=>m?.text)||"";return <button onClick={()=>onOpen(chat)} style={{...base,width:"100%",display:"block",margin:"3px 0",padding:"10px 11px",border:0,borderRadius:10,background:"#151515",color:"#eee",textAlign:"left",cursor:"pointer"}}><div style={{fontSize:12,fontWeight:700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{chat.title||"New chat"}</div><div style={{marginTop:3,fontSize:10,color:"#888",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{last}</div></button>}
function Actions({close}){const items=[["↗","Share"],["▣","Uploaded files"],["⌫","Delete"],["⌕","Find chat"],["⌑","Pin"],["✦","Create priority project"],["＋","Add shortcut"]];return <div style={{...base,position:"fixed",inset:0,zIndex:2147483000,pointerEvents:"auto"}}><button onClick={close} style={{position:"absolute",inset:0,width:"100%",height:"100%",border:0,background:"rgba(0,0,0,.5)"}}/><div style={{...base,position:"absolute",right:12,top:62,width:"min(290px,calc(100vw - 24px))",padding:10,border:"1px solid #292929",borderRadius:16,background:"#101010",boxShadow:"0 20px 60px rgba(0,0,0,.6)"}}><div style={{...base,display:"flex",justifyContent:"space-between",padding:"7px 8px 12px",color:"#fff",fontSize:13,fontWeight:800}}>Chat options<button onClick={close} style={{border:0,background:"transparent",color:"#999",fontSize:22}}>×</button></div>{items.map(([icon,label])=><button key={label} onClick={()=>{if(label==="Share"&&navigator.share)navigator.share({title:"ROYEXA CRM",text:"ROYEXA CRM workspace"}).catch(()=>{});close()}} style={{...base,width:"100%",display:"flex",gap:12,alignItems:"center",padding:"12px",margin:"3px 0",border:0,borderRadius:10,background:"#171717",color:"#eee",fontSize:12,textAlign:"left"}}><span>{icon}</span>{label}</button>)}</div></div>}
function BottomNav(){const[active,setActive]=useState("dashboard");useEffect(()=>{const onHome=()=>setActive("dashboard");window.addEventListener("royexa:home-open",onHome);return()=>window.removeEventListener("royexa:home-open",onHome)},[]);const items=[["dashboard","⌂","Home"],["leads","◎","Leads"],["messages","◌","Messages"],["followups","◷","Follow-ups"],["email","@","Gmail"],["analytics","◒","Analysis"],["automations","⚡","Automation"],["intelligence","◈","Intelligence"]];return <nav aria-label="Primary mobile navigation" style={{...base,position:"fixed",left:0,right:0,bottom:0,zIndex:2147482000,display:"flex",flexDirection:"row",alignItems:"center",justifyContent:"space-around",gap:0,overflow:"hidden",padding:"7px 4px calc(7px + env(safe-area-inset-bottom))",background:"rgba(8,8,8,.98)",borderTop:"1px solid #292929",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)",pointerEvents:"auto"}}>{items.map(([id,icon,label])=><button key={id} type="button" onClick={()=>{setActive(id);route(id)}} aria-label={label} title={label} style={{...base,flex:"1 1 0",minWidth:0,height:44,minHeight:44,border:0,outline:"none",background:"transparent",color:active===id?"#fff":"#777",borderRadius:10,fontSize:21,lineHeight:1,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",touchAction:"manipulation",WebkitTapHighlightColor:"transparent",pointerEvents:"auto"}}>{icon}</button>)}</nav>}
function Nav(){const[actions,setActions]=useState(false);useEffect(()=>{const b=()=>setActions(true);window.addEventListener("royexa:chat-options-open",b);return()=>window.removeEventListener("royexa:chat-options-open",b)},[]);return <><BottomNav/>{actions&&<Actions close={()=>setActions(false)}/>}</>}
function mount(){let root=document.getElementById("royexa-mobile-nav-root");if(!root){root=document.createElement("div");root.id="royexa-mobile-nav-root";root.style.cssText="position:fixed;inset:0;z-index:2147483000;pointer-events:none;";document.body.appendChild(root)}createRoot(root).render(<Nav/>);root.style.pointerEvents="none"}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();