import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./mobile-nav.css";
const labels={dashboard:["Dashboard","Home"],leads:["Leads"],conversations:["Conversations","Messages"],analytics:["Analysis","Analytics"],followup:["Follow-up","Follow Ups"]};
function buttons(){return[...document.querySelectorAll("button,a,[role='button']")];}
function findAndClick(names){const wanted=names.map(x=>x.toLowerCase());const hit=buttons().find(el=>wanted.some(x=>{const t=(el.textContent||"").trim().toLowerCase();return t===x||t.includes(x)}));if(hit){hit.click();return true}return false}
function emit(event){window.dispatchEvent(new Event(event));}
function openNotifications(){if(findAndClick(["Notifications","Notification"]))return;emit("royexa:notifications-open");}
function openMakePost(){if(findAndClick(["Make Post","Schedule Social","Schedule a Post"]))return;const tools=findAndClick(["CRM Tools"]);if(tools){setTimeout(()=>{if(!findAndClick(["Schedule Social","Schedule a Post","Make Post"]))emit("royexa:social-scheduler-open")},100);return}emit("royexa:client-tools");setTimeout(()=>{if(!findAndClick(["Schedule Social","Schedule a Post","Make Post"]))emit("royexa:social-scheduler-open")},100);}
function openCalendar(){if(findAndClick(["Google Calendar","Calendar"]))return;emit("royexa:calendar-open");}
function openWhatsApp(){if(findAndClick(["Connect WhatsApp","WhatsApp"]))return;emit("royexa:whatsapp-open");}
function Nav(){const[more,setMore]=useState(false);const close=()=>setMore(false);const go=id=>{if(id==="ai"){emit("royexa:assistant-open");return}if(id==="more"){setMore(v=>!v);return}findAndClick(labels[id]||[id])};const item=(label,icon,handler)=><button type="button" onClick={()=>{close();handler()}}>{icon} {label}</button>;return <><nav className="royexa-mobile-nav"><button onClick={()=>go("dashboard")}>⌂<span>Home</span></button><button onClick={()=>go("leads")}>👥<span>Leads</span></button><button onClick={()=>go("conversations")}>💬<span>Messages</span></button><button className="royexa-ai-nav" onClick={()=>go("ai")}>✨<span>AI</span></button><button onClick={()=>go("more")}>☰<span>More</span></button></nav>{more&&<div className="royexa-mobile-sheet">{item("Notifications","🔔",openNotifications)}{item("Make Post","📅",openMakePost)}{item("Gmail","✉️",()=>{if(!findAndClick(["Gmail","Google Gmail"]))emit("royexa:gmail-open")})}{item("Calendar","📆",openCalendar)}{item("WhatsApp","🟢",openWhatsApp)}{item("Analysis","📈",()=>{if(!findAndClick(["Analysis","Analytics"]))emit("royexa:analytics-open")})}<button type="button" onClick={close}>Close</button></div>}</>}
function mount(){if(document.getElementById("royexa-mobile-nav-root"))return;const n=document.createElement("div");n.id="royexa-mobile-nav-root";document.body.appendChild(n);createRoot(n).render(<Nav/>)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();