import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{createClient}from"@supabase/supabase-js";import"./royexa-home.css";
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
function showHome(show){const root=document.getElementById("royexa-home-root"),main=document.querySelector(".app > main");if(!root||!main)return;root.style.display=show?"block":"none";main.classList.toggle("royexa-home-active",show)}
async function fn(name,body){const{data,error}=await supabase.functions.invoke(name,{body});if(error)throw error;return data||{}}
function bullets(items,empty="None returned."){return Array.isArray(items)&&items.length?items.map(x=>`• ${typeof x==="string"?x:(x.title||x.label||x.recommended_action||JSON.stringify(x))}`).join("\n"):empty}
async function routeExistingIntelligence(text){const q=text.toLowerCase();
if(/\b(prepare|prep)\b.*\b(me|my)\b.*\b(meeting|meetings|call)\b|\bmeeting prep\b/.test(q)){const r=await fn("meeting-prep-v3",{query:text});if(r?.ok&&r?.found&&r?.brief){const b=r.brief,c=r.contact;return `Meeting preparation ready.\n\n${b.brief||`Meeting: ${b.meeting_title||"Upcoming meeting"}. Contact: ${c?.name||"Unknown"}.`}\n\nAgenda\n${bullets(b.agenda)}\n\nQuestions\n${bullets(b.questions)}${(b.risks||[]).length?`\n\nRisks\n${bullets(b.risks)}`:""}`}return r?.message||"I couldn't find a matching meeting to prepare for."}
if(/\b(daily brief|executive brief|what needs my attention today|today's priorities|today priorities)\b/.test(q)){const r=await fn("royexa-ai-orchestrator-v2",{action:"daily"});if(!r?.ok)throw Error(r?.error||"Daily briefing failed");const a=r.analysis||{};return `${a.summary||"Here is your executive brief."}\n\nPriorities\n${bullets(a.priorities,"• No priority items returned.")}\n\nOverdue follow-ups: ${r.counts?.overdue_followups??0}\nOverdue tasks: ${r.counts?.overdue_tasks??0}\nLeads: ${r.counts?.leads??0}`}
if(/\b(memory|remember|what do you remember)\b/.test(q)){const r=await fn("royexa-ai-orchestrator-v2",{action:"memory_list"});if(!r?.ok)throw Error(r?.error||"Memory request failed");const items=r.memory||[];return items.length?`Business memory\n\n${items.slice(0,12).map(m=>`• ${m.title}: ${m.content}`).join("\n")}`:"ROYEXA has no saved business memories yet."}
if(/\b(intelligence|intelligent|score|scoring|forecast|forecasting|high potential|at risk|pipeline risk|close probability|lead score)\b/.test(q)){const r=await fn("royexa-intelligence-engine",{mode:/\b(score|scoring|lead score)\b/.test(q)?"score_all":"dashboard"});if(r?.error)throw Error(r.error);const s=r.summary||{};const top=r.topOpportunities||r.results||r.intelligence||[];const risk=r.atRisk||[];return `ROYEXA Intelligence\n\nOpen pipeline: ${s.openPipeline??0}\nForecast: ${s.forecast??0}\nHigh potential: ${s.highPotential??top.filter(x=>Number(x.score)>=70).length}\nAt risk: ${s.atRisk??risk.length}\n\nTop opportunities\n${bullets(top.slice(0,6),"• No scored opportunities returned.")}\n\nPipeline risk\n${bullets(risk.slice(0,6),"• No high-risk opportunities returned.")}`}
if(/\b(omnichannel|channels|connected channels|channel health|whatsapp|gmail|email integration|website channel|social channel)\b/.test(q)){const{data:{session}}=await supabase.auth.getSession();const{data}=await supabase.from("omnichannel_connections").select("channel,status").eq("user_id",session.user.id).order("channel");return `Omnichannel status\n\n${(data||[]).map(c=>`• ${c.channel}: ${c.status}`).join("\n")||"• No channel records yet."}`}
if(/\b(which leads|leads need|lead attention|sales opportunities|pipeline|follow.?ups? overdue|analy[sz]e my|business analysis|what should i do next|next actions)\b/.test(q)){const r=await fn("royexa-ai-orchestrator-v2",{action:"analyze",command:text});if(!r?.ok)throw Error(r?.error||"Business analysis failed");return `${r.answer||"Analysis complete."}${(r.actions||[]).length?`\n\nRecommended actions\n${r.actions.map(a=>`• ${a.label||a.type}`).join("\n")}`:""}`}
return null}
function Home(){const[business,setBusiness]=useState("there"),[prompt,setPrompt]=useState(""),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[chatId,setChatId]=useState(null);useEffect(()=>{(async()=>{try{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const{data}=await supabase.from("workspaces").select("business_name,display_name").eq("owner_id",session.user.id).maybeSingle();if(data?.display_name||data?.business_name)setBusiness(data.display_name||data.business_name);const{data:chat}=await supabase.from("ai_chats").select("id,messages").eq("user_id",session.user.id).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(chat){setChatId(chat.id);setMessages(Array.isArray(chat.messages)?chat.messages:[])}}catch(_){}})();const onHome=()=>showHome(true);const onChat=e=>{showHome(true);const d=e.detail||{};setChatId(d.id||null);setMessages(Array.isArray(d.messages)?d.messages:[]);setError("")};window.addEventListener("royexa:home-open",onHome);window.addEventListener("royexa:chat-open",onChat);return()=>{window.removeEventListener("royexa:home-open",onHome);window.removeEventListener("royexa:chat-open",onChat)}},[]);
async function persist(next){try{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const title=next.find(m=>m.role==="user")?.text?.slice(0,80)||"New chat";if(chatId){await supabase.from("ai_chats").update({title,messages:next,updated_at:new Date().toISOString()}).eq("id",chatId);return}const{data,error}=await supabase.from("ai_chats").insert({user_id:session.user.id,title,messages:next}).select("id").single();if(error)throw error;setChatId(data.id)}catch(e){console.warn("Chat persistence failed",e)}}
async function ask(){const text=prompt.trim();if(!text||busy)return;setPrompt("");setError("");const next=[...messages,{role:"user",text}];setMessages(next);setBusy(true);try{const{data:{session},error:authError}=await supabase.auth.getSession();if(authError||!session)throw Error("Please sign in to use ROYEXA AI.");let answer=await routeExistingIntelligence(text);if(answer===null){const history=next.slice(-20).map(m=>({role:m.role,content:m.text}));const{data:result,error}=await supabase.functions.invoke("ai-crm-assistant",{body:{action:"chat",message:text,history}});if(error)throw error;answer=String(result?.result||result?.message||result?.answer||"ROYEXA couldn't generate a response.")}const completed=[...next,{role:"assistant",text:answer}];setMessages(completed);await persist(completed);window.dispatchEvent(new Event("royexa:recent-chats-refresh"))}catch(e){setError(e?.message||"AI request failed");setMessages(m=>m.slice(0,-1))}finally{setBusy(false)}}
return <div className="royexa-home"><header className="royexa-home-top"><button className="royexa-home-menu" onClick={()=>window.dispatchEvent(new Event("royexa:mobile-drawer-open"))} aria-label="Open CRM navigation">☰</button><div className="royexa-home-brand">ROYEXA <span>CRM</span></div><div className="royexa-home-right"><button className="royexa-home-notify" onClick={()=>window.dispatchEvent(new Event("royexa:notifications-open"))} aria-label="Notifications">🔔</button><button className="royexa-home-more" onClick={()=>window.dispatchEvent(new Event("royexa:chat-options-open"))} aria-label="Open chat options">⋮</button></div></header>{messages.length>0&&<section className="royexa-home-chat">{messages.map((m,i)=><div key={i} className={m.role==="user"?"royexa-home-user":"royexa-home-ai"}><b>{m.role==="user"?"You":"ROYEXA"}</b><div>{m.text}</div></div>)}{busy&&<div className="royexa-home-ai"><b>ROYEXA</b><div>Working…</div></div>}{error&&<div className="royexa-home-error">{error}</div>}</section>}{messages.length===0&&<section className="royexa-home-center"><h1>Good to see you, {business}.</h1><p>What can I help you with?</p></section>}<form className="royexa-home-command" onSubmit={e=>{e.preventDefault();ask()}}><span>✦</span><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask ROYEXA anything…"/><button type="submit" disabled={!prompt.trim()||busy} aria-label="Send">↑</button></form></div>}
function bindRouting(){const main=document.querySelector(".app > main");if(!main)return false;[...main.querySelectorAll("button")].forEach(btn=>{if(btn.dataset.royexaHomeBound)return;const text=(btn.textContent||"").trim().toLowerCase();if(text.includes("dashboard"))btn.addEventListener("click",()=>showHome(true));else if(text.includes("growth analytics")||text.includes("follow-ups")||text==="leads"||text==="messages")btn.addEventListener("click",()=>showHome(false));btn.dataset.royexaHomeBound="1"});return true}
function mount(){if(document.getElementById("royexa-home-root"))return true;const main=document.querySelector(".app > main");if(!main)return false;const root=document.createElement("div");root.id="royexa-home-root";main.prepend(root);createRoot(root).render(<Home/>);bindRouting();showHome(true);const observer=new MutationObserver(()=>bindRouting());observer.observe(main,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),15000);return true}
function boot(){if(mount())return;const observer=new MutationObserver(()=>{if(mount())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),15000)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();